additionalpages/urls.py
from django.urls import path
from . import views

app_name = 'additionalpages'

urlpatterns = [
    path('organisasi/', views.organisasi, name='organisasi'),
    path('kepanitiaan/', views.kepanitiaan, name='kepanitiaan'),
    path('matakuliah/', views.matakuliah, name ='matakuliah'),
    path('matakuliah/savematakuliah', views.savematakuliah),
    path('showmatakuliah/', views.showmatakuliah, name = 'show'),
    path('showmatakuliah/savematakuliah', views.showmatakuliah),
    path('hapusmatakuliah/<int:id>', views.hapusmatakuliah),
    path('detailmatakuliah/<int:id>', views.detail, name = 'detail'),
    # dilanjutkan ...
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.efrin, name='efrin'),
    # dilanjutkan ...
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('homepage.urls', 'homepage'), namespace = 'homepage' )),
    path('', include(('additionalpages.urls', 'additionalpages'), namespace = 'additionalpages' )),
    path('', include(('story6.urls', 'story6'), namespace = 'story6'))
]

story6/urls.py
from django.urls import path,include
from django.shortcuts import render
from django.conf.urls import url
from . import views

app_name = 'story6'

urlpatterns = [
    path('kegiatan/', views.createKegiatan, name = 'kegiatan'),
    path('create/<int:siswa_id>', views.createSiswa, name = 'create')
    # dilanjutkan ...
]

additionalpages/models.py
# Create your models here.
from django.db import models

class MataKuliah(models.Model): #class model
    nama_mata_kuliah = models.CharField(max_length=20, blank= False)
    dosen_pengajar = models.CharField(max_length=30, blank= False)
    jumlah_sks = models.IntegerField(blank= False)
    deskripsi_mata_kuliah = models.CharField(max_length=40, blank= False)
    semester_tahun = models.CharField(max_length=20, blank= False)
    ruang_kelas = models.CharField(max_length=10, blank= False)

class Meta :
    db_table = 'dt_matakuliah' #menamai tabel pada database

homepage/models.py
from django.db import models

# Create your models here.

story6/models.py
from django.db import models

class listKegiatan(models.Model):
	namaKegiatan = models.TextField(max_length=300)

	def __str__(self):
		return self.namaKegiatan

class listSiswa(models.Model):
	namaSiswa = models.TextField(max_length=300)
	kegiatan = models.ForeignKey(listKegiatan, on_delete=models.CASCADE)

	def __str__(self):
		return self.namaSiswa

additionalpages/forms.py
from additionalpages.models import MataKuliah
from django import forms

class Input_Form(forms.ModelForm):
    class Meta:
        model = MataKuliah
        fields = "__all__" #ambil semua yang terdapat pada model

#dari sini kebawah
    error_messages = {
        'required' : 'Please Type'
    }
    input_attrs = {
        'type' : 'text',
        'placeholder' : 'Nama Mata Kuliah'
    }

    input_attrs1 = {
        'type' : 'text',
        'placeholder' : 'Nama Dosen Pengajar'
    }

    input_attrs2 = {
        'type' : 'text',
        'placeholder' : 'jumlah SKS'
    }

    input_attrs3 = {
        'type' : 'text',
        'placeholder' : 'Deskripsi Mata Kuliah'
    }

    input_attrs4 = {
        'type' : 'text',
        'placeholder' : 'Semester Tahun'
    }

    input_attrs5 = {
        'type' : 'text',
        'placeholder' : 'Ruang Kelas'
    }

    nama_mata_kuliah = forms.CharField(label='', required=True,
        max_length=20, widget=forms.TextInput(attrs=input_attrs))
    dosen_pengajar = forms.CharField(label='', required=True,
        max_length=30, widget=forms.TextInput(attrs=input_attrs1))
    jumlah_sks = forms.IntegerField(label='', required=True, widget=forms.TextInput(attrs=input_attrs2)) 
    deskripsi_mata_kuliah = forms.CharField(label='', required=True,
        max_length=40, widget=forms.TextInput(attrs=input_attrs3))
    semester_tahun = forms.CharField(label='', required=True,
        max_length=20, widget=forms.TextInput(attrs=input_attrs4))
    ruang_kelas = forms.CharField(label='', required=True,
        max_length=10, widget=forms.TextInput(attrs=input_attrs5))



    



    

story6/forms.py
from django import forms
from . import models

class formKegiatan(forms.Form):
	namaKegiatan = forms.CharField(max_length=300,required=True)

class formSiswa(forms.Form):
	namaSiswa = forms.CharField(max_length=300)

additionalpages/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from additionalpages.models import MataKuliah
from additionalpages.forms import Input_Form
from django.template import response
from additionalpages import models
# Create your views here
    
def organisasi(request):
    response = {'title_html' : 'Organisasi'}
    return render(request, 'organisasi.html', response)

def kepanitiaan(request):
    response = {'title_html' : 'Kepanitiaan'}
    return render(request, 'kepanitiaan.html', response)


def matakuliah(request):
    response = {'input_form' : Input_Form(), 'title_html' : 'Mata Kuliah'}
    return render(request, 'matakuliah.html', response)

#ngambil form dari forms.py
def savematakuliah(request):
    form = Input_Form(request.POST or None)
    if (request.method == 'POST') :
        if (form.is_valid()) :
            form.save()
            return HttpResponseRedirect('/showmatakuliah')
        else :
            return HttpResponseRedirect('/')
    else :
        return HttpResponseRedirect('/')

#menampilan matakuliah yang sudah ditambahkan
def showmatakuliah(request):
    matakuliah = MataKuliah.objects.all() #mengambil data dari data base melalui models
    response= {'matkuls' : matakuliah} #ini untuk ngisi variabel
    return render(request, 'matakuliah.html', response)

def hapusmatakuliah(request, id):
    matakuliah = MataKuliah.objects.get(id=id)
    matakuliah.delete()
    return HttpResponseRedirect('/showmatakuliah')

def detail(request,id) :
    matakuliah = MataKuliah.objects.get(id=id)
    response={'matkuls' : matakuliah, 'title_html' : 'Detail Mata Kuliah' }
    return render(request, 'detailmatakuliah.html', response)

homepage/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def efrin(request):
    response = {'title_html' : 'My Biodata'}
    return render(request, 'efrin.html', response)

story6/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import *

# Create your views here.

def createKegiatan(request):
	kegiatan= listKegiatan.objects.all()
	kegiatann=formKegiatan(request.POST or None)
	context={
		'kegiatan':kegiatan,
		'kegiatann':kegiatann
	}
	if request.method=='POST':
		if kegiatann.is_valid():
			kegiatan.create(
				namaKegiatan=kegiatann.cleaned_data.get('namaKegiatan')
				)
	return render(request,'kegiatan.html',context)

def createSiswa(request, siswa_id):
	siswa= listKegiatan.objects.get(id=siswa_id)
	siswaTarget = listSiswa.objects.all()
	form_siswa = formSiswa(request.POST or None)
	context={
		'siswa':siswa,
		'form_siswa':form_siswa,
		'siswa_target':siswaTarget,
	}
	if request.method=='POST':
		if form_siswa.is_valid():
			siswaTarget.create( #memasukkan siswa ke kegiatan tertentu
					namaSiswa=form_siswa.cleaned_data.get('namaSiswa'),
					kegiatan=siswa
				)
	return render(request,'peserta.html',context)

additionalpages/templates/detailmatakuliah.html
<!DOCTYPE html>
{% include "navbar.html" %}
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">

        <title>{{title_html}}</title>
    </head>
 
<body>
    {% block content %}
    <div class="container-fluid" style="background-color: #75c7f4;">
        <div class = "container-fluid">
            <div class="row">
                <div class="col-sm-7 col-md-9">
                    <div class = "container-fluid" style="background-color:#8ee7b3ab; min-width: fit-content;">
                        <div class="row">
                            <div class="col-sm-12 col-md-12">
                                <h2>Detail Mata Kuliah {{matkuls.nama_mata_kuliah}}</h2>
                            </div>
                            <div class="col-sm-12 col-md-12" style="margin-top: 20px;">
                                <table class="tables">
                                    <tr>
                                        <th class="tables">Nama Dosen Pengajar</th> 
                                        <th class="tables">Jumlah SKS</th> 
                                        <th class="tables">Deskripsi</th> 
                                        <th class="tables">Semester Tahun</th> 
                                        <th class="tables">Ruang Kelas</th> 
                                    </tr>

                                    <tr>
                                        <td class="tables">{{matkuls.dosen_pengajar}}</td>
                                        <td class="tables">{{matkuls.jumlah_sks}}</td>
                                        <td class="tables">{{matkuls.deskripsi_mata_kuliah}}</td>
                                        <td class="tables">{{matkuls.semester_tahun}}</td>
                                        <td class="tables">{{matkuls.ruang_kelas}}</td>
                                    </tr>
                                </table>
                                <div class="col-sm-12 col-md-12">
                                    <a href ="/matakuliah" class = "btn btn-primary">Tambah Mata Kuliah</a>
                                    <a href ="/showmatakuliah" class = "btn btn-primary">Daftar Mata Kuliah</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% endblock %}
</body>
</html>

additionalpages/templates/kepanitiaan.html
<!DOCTYPE html>
{% include "navbar.html" %}
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">

        <title>{{title_html}}</title>
    </head>

<body>
    {% block content %}
    <div class="container-fluid" style="background-color: #75c7f4;">
        <div class = "container-fluid">
            <div class="row">
                <div class="col-sm-7 col-md-9">
                    <div class = "container-fluid" style="background-color:#8ee7b3ab; min-width: fit-content; height: 465px;">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="tables">
                                    <tr><th class="tables"><b>No.</b></th> 
                                        <th class="tables"><b>Nama Kepanitiaan</b></th> 
                                        <th class="tables"><b>Tahun</b></th>
                                    </tr>
                                    <tr>
                                        <td class="tables">1</td>
                                        <td class="tables">Gelar Karya</td> 
                                        <td class="tables">2019</td> 
                                    </tr>
                                    <tr>
                                        <td class="tables">2</td>
                                        <td class="tables">Social Project PMB</td> 
                                        <td class="tables">2019</td> 
                                    </tr>
                                    <tr>
                                        <td class="tables">3</td>
                                        <td class="tables">BETIS</td> 
                                        <td class="tables">2020</td> 
                                    </tr>
                                    <tr>
                                        <td class="tables">4</td>
                                        <td class="tables">WISGEN</td> 
                                        <td class="tables">2020</td> 
                                    </tr>
                                    <tr>
                                        <td class="tables">5</tb>
                                        <td class="tables">SIWAK</td> 
                                        <td class="tables">2020</td> 
                                    </tr>
                                    <tr>
                                        <td class="tables">6</tb>
                                        <td class="tables">MTQ UI</td> 
                                        <td class="tables">2020</td> 
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card" style="width: 18rem; background-color: #E5E5E5;">
                    <div class="card-body">
                      <h5 class="card-title">{{title_html}}</h5>
                      <h6 class="card-subtitle mb-2 text-muted">Deskripsi</h6>
                      <p class="card-text">Halo semuanya! jadi ini adalah kepanitiaan yang pernah aku jalani. 
                          Baru dikit dimaafin aja la ya untuk formalitas tugas hehe. 
                      </p>
                    </div>
                  </div>
            </div>
        </div>
    </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        {% endblock  %}
    </body>
</html>

additionalpages/templates/matakuliah.html
<!DOCTYPE html>
{% include "navbar.html" %}
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">

        <title>{{title_html}}</title>
    </head>
 
<body>
    {% block content %}
    <div class="container-fluid" style="background-color: #75c7f4;">
        <div class = "container-fluid">
            <div class="row">
                <div class="col-sm-7 col-md-9">
                    <div class = "container-fluid" style="background-color:#8ee7b3ab; min-width: fit-content;">
                        <div class="row">
                            <div class="col-sm-12 col-md-12">
                                <h1>Mata Kuliah</h1>
                            </div>
                            <div class="col-sm-12 col-md-12" style="margin-top: 20px;">
                                <form action="savematakuliah" method = "POST">
                                    {% csrf_token %}
                                    <p>Nama Mata Kuliah : {{input_form.nama_mata_kuliah}}</p>
                                    <p>Dosen Pengajar : {{input_form.dosen_pengajar}}</p>
                                    <p>Jumlah SKS : {{input_form.jumlah_sks}}</p>
                                    <p>Deskripsi Mata Kuliah : {{input_form.deskripsi_mata_kuliah}}</p>
                                    <p>Semester Tahun : {{input_form.semester_tahun}}</p>
                                    <p>Ruang Kelas : {{input_form.ruang_kelas}}</p>
                                    <input type = "submit" value = "Submit"> 
                                </form>
                            </div>
                            {% if matkuls %}
                                <div class="col-sm-12 col-md-12">  
                                    <table class="tables">
                                        {% for matkul in matkuls %}
                                            <tr>  
                                                <th class="tables">Nama Mata Kuliah</th>  
                                                <th class="tables">Hapus?</th>
                                            </tr>    
                                            <tr>  
                                                <td class="tables"><a style="color: black;" href = "/detailmatakuliah/{{matkul.id}}">{{matkul.nama_mata_kuliah}}</a></td> 
                                                <td class="tables"><a href ="/hapusmatakuliah/{{matkul.id}}" class = "btn btn-primary">Hapus</a></td>
                                            </tr>
                                        {% endfor %}
                                    </table>
                                </div>
                                <div class="col-sm-12 col-md-12">
                                    <a href ="/matakuliah" class = "btn btn-primary">Tambah Mata Kuliah</a>
                                </div>
                            {% endif %}
                                <div class="col-sm-12 col-md-12">
                                    <a href ="/showmatakuliah" class = "btn btn-primary">Daftar Mata Kuliah</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% endblock %}
</body>
</html>

additionalpages/templates/organisasi.html
<!DOCTYPE html>
{% include "navbar.html" %}
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">

        <title>{{title_html}}</title>
    </head>

<body>
    {% block content %}
    <div class="container-fluid" style="background-color: #75c7f4;">
        <div class = "container-fluid">
            <div class="row">
                <div class="col-sm-7 col-md-9">
                    <div class = "container-fluid" style="background-color:#8ee7b3ab; min-width: fit-content; height: 465px;">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="tables">
                                    <tr><th class="tables"><b>No.</b></th> 
                                        <th class="tables"><b>Nama Organisasi</b></th> 
                                        <th class="tables"><b>Biro/ Departement</b></th>
                                        <th class="tables"><b>Tahun</b></th>
                                    </tr>
                                    <tr>
                                        <td class="tables">1</td>
                                        <td class="tables">BEM</td> 
                                        <td class="tables">Pengabdian Masyarakat</td> 
                                        <td class="tables">2020</td>
                                    </tr>
                                    <tr>
                                        <td class="tables">2</td>
                                        <td class="tables">FUKI</td> 
                                        <td class="tables">PSDM</td> 
                                        <td class="tables">2020</td>
                                    </tr>
                                </table>
                              </div>
                        </div>
                    </div>
                </div>
                <div class="card" style="width: 18rem; background-color: #E5E5E5;">
                    <div class="card-body">
                      <h5 class="card-title">{{title_html}}</h5>
                      <h6 class="card-subtitle mb-2 text-muted">Deskripsi</h6>
                      <p class="card-text">Halo semuanya! jadi ini adalah organisasi yang pernah aku jalani. 
                          Baru dikit dimaafin aja la ya untuk formalitas tugas hehe. 
                      </p>
                    </div>
                  </div>
            </div>
        </div>
    </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% endblock  %}
    </body>
</html>

homepage/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #555;">
    <a class="navbar-brand" href="#" style="background-color: #d7e241; border-radius: 100px;">efrin.frn</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'homepage:efrin' %}" style="color: #d7e241;">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'additionalpages:organisasi' %}" style="color: #d7e241;">Organisasi</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'additionalpages:kepanitiaan' %}" style="color: #d7e241;">Kepanitiaan</a>
                </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'additionalpages:matakuliah' %}" style="color: #d7e241;">Mata Kuliah</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'story6:kegiatan' %}" style="color: #d7e241;">Kegiatan</a>
            </li>
        </ul>
    </div>
</nav>

story6/templates/kegiatan.html
<!DOCTYPE html>
{% include "navbar.html" %}
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">

        <title>Kegiatan</title>
    </head>
<body>
	<h2>Jadwal Kegiatan</h2>

	<form method="POST">
	{% csrf_token %}
	<table>
		{{kegiatann.as_table}}
	</table>
	<button type="Submit" name="submit">Submit</button>

	<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">Nama Kegiatan</th>
    </tr>
    </thead>
    <tbody>
    	{% for keg in kegiatan %}
    	<tr>
    		<th scope="row">{{keg.namaKegiatan}}</th>
    		<td><a href="{% url 'story6:create' siswa_id=keg.id %}" class="btn btn-danger">Lihat/Add Siswa</a></td>
    	</tr>
    </tbody>
    {% endfor %}
</body>
</html>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

story6/templates/peserta.html
<!DOCTYPE html>
{% include "navbar.html" %}
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">

        <title>Peserta</title>
    </head>
<body>
	<h2>Jadwal Kegiatan</h2>

	<form method="POST">
	{% csrf_token %}
	<table>
		{{form_siswa.as_table}}
	</table>
	<button type="Submit" name="submit">Submit</button>

	<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">Nama Siswa</th>
    </tr>
    </thead>
    <tbody>
    	{% for sis in siswa_target %}
    	<tr>
            {% if sis.kegiatan == siswa %}
    		<th scope="row">{{sis.namaSiswa}}</th>
            {% endif %} 
    	</tr>
    </tbody>
    {% endfor %}
</body>
</html>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>